#!/usr/bin/env ruby
#
# This file is here to facilitate running the example code for rservicebus.
#

# Add the currently running directory to the start of the load path
$:.unshift './../../lib'

require 'rubygems'
require 'rservicebus2'

def run_rservicebus
  RServiceBus2::Host.new.run
end

run_rservicebus
